<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="NANDY" failures="2" tests="3" name="Test1" time="0.102" errors="0" timestamp="2022-08-30T16:59:17 IST">
  <testcase classname="rerunfailedtestcases.TestNGRetryFailedDemo" name="test1" time="0.016"/>
  <testcase classname="rerunfailedtestcases.TestNGRetryFailedDemo" name="test2" time="0.003">
    <failure type="java.lang.ArithmeticException" message="/ by zero">
      <![CDATA[java.lang.ArithmeticException: / by zero
at rerunfailedtestcases.TestNGRetryFailedDemo.test2(TestNGRetryFailedDemo.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="rerunfailedtestcases.TestNGRetryFailedDemo" name="test3" time="0.016">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at rerunfailedtestcases.TestNGRetryFailedDemo.test3(TestNGRetryFailedDemo.java:23)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
</testsuite> <!-- Test1 -->
